version: "3"

services:
  web:
    container_name: web
    build:
      context: ./docker/nginx
    ports:
      - "${WEB_HOST_PORT:-8080}:80"
    volumes:
      - ./src:/var/www
    depends_on:
      - app

  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www
    depends_on:
      - db
