version: "3"

services:
  web:
    container_name: web
    image: 046921553479.dkr.ecr.ap-northeast-1.amazonaws.com/daily_report_web:latest
    ports:
      - "${WEB_HOST_PORT:-80}:80"
    volumes:
      - ./src:/var/www
    depends_on:
      - app

  app:
    container_name: app
    image: 046921553479.dkr.ecr.ap-northeast-1.amazonaws.com/daily_report_app:latest
    volumes:
      - ./src:/var/www
    depends_on:
      - db
