version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    env_file: development.env
    ports:
      - '3306:3306'

  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: development.env
